SELECT dc.*
FROM ent.DYN_US dc
LEFT JOIN ent.Customers_DYNAMITE_US_DE_EngagementInfo dco ON dc.EMAIL = dco.EMAIL
WHERE (dc.LAST_OPEN_DATE > DATEADD(day, -180, GETDATE()) OR dc.LAST_CLICK_DATE > DATEADD(day, -180, GETDATE()) OR  dc.ADD_DATE > DATEADD(day, -180, GETDATE()))
OR 
(dco.LAST_OPEN_DATE > DATEADD(day, -180, GETDATE()) OR dco.LAST_CLICK_DATE > DATEADD(day, -180, GETDATE()))
