SELECT dc.*
FROM ent.GAR_CA dc
LEFT JOIN ent.Customers_GARAGE_CA_DE_EngagementInfo dco ON dc.EMAIL = dco.EMAIL
WHERE (dc.LAST_OPEN_DATE > DATEADD(day, -180, GETDATE()) OR dc.LAST_CLICK_DATE > DATEADD(day, -180, GETDATE()) OR  dc.ADD_DATE > DATEADD(day, -180, GETDATE()))
OR 
(dco.LAST_OPEN_DATE > DATEADD(day, -180, GETDATE()) OR dco.LAST_CLICK_DATE > DATEADD(day, -180, GETDATE()))
