SELECT l.EMAIL, 
    l.SUBSCRIBER_KEY, 
    MAX(l.LAST_OPEN_DATE) as LAST_OPEN_DATE,
    MAX(l.LAST_CLICK_DATE) as LAST_CLICK_DATE
    FROM ent.LOY_CA l 
    LEFT JOIN ( 
      SELECT y.SUBSCRIBER_KEY, y.LAST_OPEN_DATE, y.LAST_CLICK_DATE FROM (
        SELECT g.SUBSCRIBER_KEY, g.LAST_OPEN_DATE, g.LAST_CLICK_DATE FROM ent.GAR_CA g
        UNION ALL 
        SELECT d.SUBSCRIBER_KEY, d.LAST_OPEN_DATE, d.LAST_CLICK_DATE FROM ent.DYN_CA d ) y
      ) e ON e.SUBSCRIBER_KEY = l.SUBSCRIBER_KEY
    GROUP BY l.EMAIL, l.SUBSCRIBER_KEY